import {evaluate,budgetFor,cashAvailable,priceTier,statusLabels,validateProfile} from './finance.js';
const $=s=>document.querySelector(s);
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=(v,rounded=false)=>v===null||v===undefined?'확인 필요':v>=10000?`${(v/10000).toLocaleString('ko-KR',{maximumFractionDigits:rounded?1:2})}억`:`${Math.round(v).toLocaleString('ko-KR')}만원`;
const monthly=v=>`${Math.round(v).toLocaleString('ko-KR')}만원`;
const safeUrl=url=>{try{const u=new URL(url);return u.protocol==='https:'?u.href:'#';}catch{return '#';}};
const link=(url,title,cls='source-link')=>`<a class="${cls}" href="${escape(safeUrl(url))}" target="_blank" rel="noopener noreferrer">${escape(title)} ↗</a>`;
const form=$('#finance-form');
const state={data:null,policy:null,region:'all',area:'84',search:'',sort:'price',affordable:false,favoritesOnly:false,compared:[],favorites:new Set(),profile:null};
try{const favorites=JSON.parse(localStorage.getItem('jip-favorites')||'[]');if(Array.isArray(favorites))state.favorites=new Set(favorites.filter(v=>typeof v==='string'));}catch{}
function readProfile(){const f=new FormData(form),p={};for(const [k,v] of f)p[k]=['homeStatus'].includes(k)?v:v==='on'?true:v.trim()===''?NaN:Number(v);p.depositReady=f.has('depositReady');p.creditRestriction=f.has('creditRestriction');return p;}
state.profile=readProfile();
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('visible'),2800);}
function naver(a){return a.naverUrl||`https://search.naver.com/search.naver?query=${encodeURIComponent(a.address+' '+a.name+' 네이버 부동산')}`;}
function naverLabel(a){return a.naverUrl?'네이버 매물 보기':'네이버에서 매물 찾기';}
function getApartment(id){return state.data.apartments.find(a=>a.id===id);}
function result(a,price=a.prices[state.area]?.amount){return evaluate(price,state.profile,{regulated:a.regulated??true});}
function renderBudget(){
  const p=state.profile,stable=budgetFor(p,true),max=budgetFor(p,false);
  $('#budget-summary').innerHTML=`<div class="budget-cell"><span class="budget-label">비상금과 생활을 지키는</span><div class="budget-value">${stable===null?'별도 심사':money(stable,true)} <span>${stable===null?'':'까지'}</span></div><p>안정 예산 · 소득 감소와 금리 상승 고려</p></div><div class="budget-cell"><span class="budget-label">현재 조건으로 계산한</span><div class="budget-value">${max===null?'별도 심사':money(max,true)} <span>${max===null?'':'까지'}</span></div><p>최대 예산 · 가용 자기자금 ${money(cashAvailable(p))}</p></div><div class="budget-foot"><span>규제지역 LTV 40% · DSR 40% 시나리오 · 은행 심사 전</span><button data-action="policy">계산 가정 확인 ↗</button></div>`;
}
function priceCell(a,area){const p=a.prices[area];return `<div class="price-cell ${state.area===area?'focus':''}"><small>전용 ${area}㎡급 ${area==='84'?'· 국평':''}</small><strong>${p?'약 '+money(p.amount,true):'미확인'}</strong><span class="date">${p?`${escape(p.date)} · 참고가격`:'단지 상세에서 확인'}</span></div>`;}
function card(a){
  const p=a.prices[state.area],e=result(a),tier=priceTier(p?.amount);
  const saved=state.favorites.has(a.id),compared=state.compared.includes(a.id);
  return `<article class="apartment-card"><div class="card-top"><span class="area-name">${escape(a.region+' · '+a.district+' '+a.dong)}</span><button class="favorite ${saved?'saved':''}" data-favorite="${escape(a.id)}" aria-label="${escape(a.name)} 관심 ${saved?'해제':'저장'}" aria-pressed="${saved}">${saved?'♥':'♡'}</button></div><div class="card-main"><button class="card-title" data-detail="${escape(a.id)}">${escape(a.name)}</button><div class="card-meta"><span>${a.households.toLocaleString()}세대</span><span>·</span><span>${a.year}년 준공</span><span>·</span><span>${a.region==='서울'?'서울':'경기'}</span></div><div class="card-tags">${tier?`<span class="tag tier">가격 ${tier}군 · ${state.area}㎡</span>`:''}${a.tags.slice(0,2).map(t=>`<span class="tag">${escape(t)}</span>`).join('')}</div><div class="prices">${priceCell(a,'59')}${priceCell(a,'84')}</div><p class="card-analysis">${escape(a.summary)}</p><div class="affordability ${e?.status||''}"><span>${e?statusLabels[e.status]:'가격 확인 필요'}</span><span>${!e?'평형 선택 확인':!e.supported?'상세 조건 확인':e.shortage>=.01?money(e.shortage,true)+' 부족':'월 '+monthly(e.monthly)}</span></div></div><div class="card-actions"><button data-compare="${escape(a.id)}" aria-pressed="${compared}">${compared?'✓ 비교함에 담김':'＋ 비교하기'}</button>${link(naver(a),naverLabel(a),'naver-link')}</div></article>`;
}
function renderList(){
  if(!state.data)return;
  const query=state.search.trim().toLowerCase();
  let list=state.data.apartments.filter(a=>a.households>=400&&(state.region==='all'||a.region===state.region)&&(!query||(a.name+a.address).toLowerCase().includes(query))&&(!state.favoritesOnly||state.favorites.has(a.id)));
  if(state.affordable)list=list.filter(a=>['safe','stretch'].includes(result(a)?.status));
  list.sort((a,b)=>{if(state.sort==='households')return b.households-a.households;if(state.sort==='newest')return b.year-a.year;const av=a.prices[state.area]?.amount,bv=b.prices[state.area]?.amount;if(!av)return bv?1:0;if(!bv)return -1;return state.sort==='price-desc'?bv-av:av-bv;});
  $('#result-count').innerHTML=`<strong>${list.length}개</strong> 단지 · 초기 조사 ${state.data.apartments.length}개 중`;
  $('#apartments').innerHTML=list.length?list.map(card).join(''):`<div class="empty-state"><strong>조건에 맞는 단지가 없어요.</strong><br>현재는 초기 조사 단지만 제공해요.<br>지역·평형·예산 필터를 바꿔보세요.<br><button class="outline-button" data-action="clear-filters">검색 조건 초기화</button></div>`;
  $('#compare-count').textContent=state.compared.length;
}
function openModal(title,html,kicker='JIP STANDARD'){ $('#modal-kicker').textContent=kicker;$('#modal-body').innerHTML=`<h2 id="modal-title">${escape(title)}</h2>${html}`;if(!$('#modal').open)$('#modal').showModal();$('#modal').scrollTop=0; }
function priceDetail(a,area){const p=a.prices[area];return `<div><small>전용 ${area}㎡급</small><strong>${p?'약 '+money(p.amount,true):'가격 확인 필요'}</strong><p>${p?'원자료 '+p.amount.toLocaleString('ko-KR')+'만원<br>'+escape(p.kind):escape(a.missing?.[area]||'확인된 거래 자료가 없습니다.')}<br>${p?`${escape(p.date)}${p.area?' · '+p.area+'㎡':''}${p.floor?' · '+p.floor+'층':''}`:''}${p?.sampleCount?'<br>'+p.sampleCount+'건 · '+p.periodDays+'일 집계':''}</p>${p?link(p.source,'가격 출처'):''}</div>`;}
function detail(id){
  const a=getApartment(id);if(!a)return;
  const p=a.prices[state.area];
  openModal(a.name,`<p class="detail-meta">${escape(a.address)} · ${a.households.toLocaleString()}세대 · ${a.year}년 준공</p><div class="detail-prices">${priceDetail(a,'59')}${priceDetail(a,'84')}</div><p class="notice">참고가격은 현재 매물 가격이 아닙니다. ${escape(state.data.priceMethod)}</p><div class="detail-grid"><section><h3>확인된 단지 정보</h3><ul>${a.facts.map(t=>`<li>${escape(t)}</li>`).join('')}</ul>${link(a.factSource||a.source,'단지 정보 출처')}</section><section><h3>현장에서 살펴볼 점</h3><ul>${a.checks.map(t=>`<li>${escape(t)}</li>`).join('')}</ul></section></div><h3>급지 · 커뮤니티</h3><div class="score-empty">${p?`선택 평형의 <strong>가격 ${priceTier(p.amount)}군</strong>입니다. `:''}가격군은 금액 구간 분류이며 입지 급지가 아닙니다. 입지·단지 품질 점수는 교통·학교·시설 자료 검증 후 제공됩니다.<br>커뮤니티: ${escape(a.facilities)}</div><section class="detail-calculator"><h3 style="margin-top:0">이 집, 내 조건으로 계산하면?</h3><p style="margin-bottom:12px">실제 보신 매물 가격으로 바꿔 계산할 수 있어요.</p><div class="two-fields"><label class="field">예상 매매가 (만원)<span class="input-wrap"><input id="detail-price" type="number" min="1" max="10000000" step="100" value="${p?.amount||''}" placeholder="가격 입력"><span>만원</span></span></label><label class="field">지역 규제 조건<select id="detail-regulation"><option value="true">규제지역 · LTV 40% 가정</option><option value="false">비규제지역 · LTV 70% 가정</option></select></label></div><p class="field-help" style="margin:0 0 14px">${a.regulated===null?'지역 지정 상태 미검증: 보수적으로 규제지역을 가정합니다.':'초기 조사 기준 규제지역을 가정합니다. 현재 지정·경과조건은 은행 확인이 필요합니다.'} 담보평가액=매매가 가정.</p><div id="detail-result" aria-live="polite"></div></section><div class="detail-actions">${link(naver(a),naverLabel(a),'primary')}${link('https://rt.molit.go.kr/','국토부에서 재확인','outline-button')}<button class="outline-button" data-compare="${a.id}">비교함에 담기</button></div>`,'APARTMENT REPORT');
  const update=()=>{const value=Number($('#detail-price').value);const container=$('#detail-result');if(!$('#detail-price').value||value<=0||!Number.isFinite(value)||value>10000000){container.innerHTML='<p>1~10,000,000만원 범위로 예상 매매가를 입력해주세요.</p>';return;}const e=evaluate(value,state.profile,{regulated:$('#detail-regulation').value==='true'});container.innerHTML=calculationHtml(e);};
  $('#detail-price').addEventListener('input',update);$('#detail-regulation').addEventListener('change',update);update();
}
function calculationHtml(e){
  if(!e.supported)return '<p class="notice">현재 주택 보유·생애최초·신용대출 조건은 이 일반 시나리오로 판정할 수 없습니다. 별도 상품 자격과 은행 심사가 필요해 대출 가능액을 표시하지 않습니다.</p>';
  const stat=(label,value)=>`<div class="detail-stat"><span>${label}</span><strong>${value}</strong></div>`;
  return `<div class="detail-result">${stat('참고 시나리오 최대 주담대',money(e.maxLoan))}${stat('구매에 사용할 추정 주담대',money(e.loan))}${stat('추가로 필요한 현금',money(e.shortage))}${stat('월 원리금 상환액',monthly(e.monthly))}${stat('매월 생활비 후 잔여',monthly(e.left))}${stat('소득 −20% · 금리 +2%p 잔여',monthly(e.stressLeft))}</div><div class="limits">${e.limits.map(l=>`<div class="limit-row"><span>${l.name}</span><strong>${money(l.amount)}</strong></div>`).join('')}<div class="limit-row"><span>취득·이사 등 비용 예산</span><strong>${money(e.costs)}</strong></div></div><p style="margin-top:12px">${statusLabels[e.status]} · 대출 제한 요인: ${e.binding}<br>필요한 자금이 최대한도보다 적으면 실제 사용할 대출을 줄여 계산합니다.</p><p class="notice">정책 예외·DTI·담보평가·방공제·전입의무·취득 제한 및 은행별 심사는 별도입니다. 이 결과는 승인 가능한 한도를 보장하지 않습니다.</p>`;
}
function comparison(){
  const list=state.compared.map(getApartment).filter(Boolean);
  if(!list.length){openModal('나란히 놓고, 더 분명하게.', '<p>아파트 카드에서 ‘비교하기’를 눌러 최대 3개 단지를 담아보세요. 가격, 세대수, 예상 대출과 월 부담을 비교할 수 있어요.</p>','COMPARE HOMES');return;}
  const row=(title,fn)=>`<tr><th>${title}</th>${list.map(a=>`<td>${fn(a)}</td>`).join('')}</tr>`;
  openModal('아파트 비교',`<p>선택 평형: 전용 ${state.area}㎡급 · 입력한 재무 조건을 공통 적용합니다.</p><div class="table-scroll"><table class="comparison-table"><thead><tr><th>비교 항목</th>${list.map(a=>`<th>${escape(a.name)}<br><button data-remove-compare="${a.id}">제외</button></th>`).join('')}</tr></thead><tbody>${row('참고가격',a=>a.prices[state.area]?'<strong>약 '+money(a.prices[state.area].amount,true)+'</strong><br>'+escape(a.prices[state.area].date):'가격 미확인')}${row('세대 / 준공',a=>`${a.households.toLocaleString()}세대<br>${a.year}년`)}${row('가격군',a=>priceTier(a.prices[state.area]?.amount)?`${priceTier(a.prices[state.area].amount)}군 · 입지 등급 아님`:'미분류')}${row('구매 시나리오',a=>result(a)?statusLabels[result(a).status]:'가격 미확인')}${row('최대 주담대',a=>result(a)?.supported?money(result(a).maxLoan):'확인 필요')}${row('부족한 현금',a=>result(a)?.supported?money(result(a).shortage):'확인 필요')}${row('월 상환액',a=>result(a)?.supported?monthly(result(a).monthly):'확인 필요')}${row('현장 확인',a=>escape(a.checks[0]))}${row('매물 확인',a=>link(naver(a),'네이버'))}</tbody></table></div><p class="notice">단지별 규제지역 정보가 미검증이면 LTV 40%를 가정합니다. 미확인 데이터는 0으로 취급하지 않습니다.</p>`,'COMPARE HOMES');
}
function method(){openModal('좋은 집을 판단하는 기준',`<p>가격과 생활의 질은 서로 다른 기준입니다. 초기 버전에서는 확인된 가격 구간과 현장 확인 항목을 제공하며, 검증하지 않은 점수는 만들지 않습니다.</p><h3>현재 제공: 평형별 가격군</h3><div class="table-scroll"><table><thead><tr><th>가격군</th><th>선택 평형 참고가격</th></tr></thead><tbody><tr><td>1군</td><td>20억원 이상</td></tr><tr><td>2군</td><td>15억 이상 ~ 20억 미만</td></tr><tr><td>3군</td><td>10억 이상 ~ 15억 미만</td></tr><tr><td>4군</td><td>7억 이상 ~ 10억 미만</td></tr><tr><td>5군</td><td>7억 미만</td></tr></tbody></table></div><p>서비스가 정한 탐색용 금액 구간입니다. 공식 급지나 투자 등급이 아니며, 59㎡와 84㎡는 각각 분류합니다.</p><h3>입지 평가 설계 · 자료 검증 후 제공</h3><p>일자리 접근 30 · 교통 20 · 교육환경 20 · 생활 인프라 15 · 주거환경 10 · 거래 안정성 5점. 학교 접근성과 실제 통학구역은 구별합니다.</p><h3>단지 품질과 커뮤니티</h3><p>건물·구조, 주차, 유지관리, 커뮤니티 운영, 조경을 확인합니다. 시설이 있다는 사실과 현재 운영 중인지는 구별하며, 미확인 시설을 ‘없음’으로 처리하지 않습니다.</p><h3>안정 예산의 기준</h3><p>서비스 제안 기준으로, 기존·신규 월 상환액 합계가 월 실수령의 35% 이내이고, 소득이 20% 감소하면서 금리가 2%p 올라도 입력한 생활비를 충당하는 범위입니다. 최대 예산도 입력한 비상금과 현재 월 생활비는 유지합니다.</p>`,'OUR METHODOLOGY');}
function policy(){const p=state.policy;openModal('대출 계산, 이렇게 가정했어요.',`<p class="notice">${escape(p.notice)}</p><p>정책 자료 조사일 ${escape(p.checkedAt)} · 계산 버전 ${escape(p.version)}</p><h3>기본 시나리오</h3><ul><li>무주택 일반 은행 주담대 · 원리금균등 · 최대 30년</li><li>DSR 40%, LTV 규제지역 40% / 비규제지역 70%</li><li>주택가격 15억 이하: 상한 6억 / 15억 초과~25억 이하: 4억 / 25억 초과: 2억</li><li>한도 심사 금리: 약정금리 가정 + 입력한 스트레스 가산금리. 실제 월 납입액은 약정금리로 계산</li><li>단지의 규제 상태를 미확인한 경우 LTV 40%를 가정. 상세에서 시나리오 변경 가능</li></ul><h3>추가 심사가 필요한 경우</h3><p>생애최초·정책모기지·기존주택 처분·다주택·경과규정은 별도 상담 대상으로 표시합니다. 1년 이내 실행한 1억원 초과 신용대출 보유자는 규제지역 계산을 보류합니다. 전세대출 상환과 전입·주택취득 제한도 은행에서 확인해야 합니다.</p><h3>부대비용과 자기자금</h3><p>기본 4%는 세법 계산값이 아닌 비용 예산입니다. 세금·중개·등기 비용에 맞춰 수정하세요. 보증금은 잔금 전 반환 확정분 중 대출 상환 후 순액만 자기자금에 포함합니다.</p><h3>확인한 공식 자료</h3>${p.sources.map(s=>`<p>${escape(s.date)} · ${link(s.url,s.title)}</p>`).join('')}<p>금융기관의 담보가액·DTI·소액임차보증금 공제·취급 한도 및 최신 법령 전체 검증은 완료되지 않았습니다.</p>`,'LENDING POLICY');}
function sources(){openModal('가격과 데이터의 출처',`<p>${escape(state.data.coverage)}</p><p class="notice">공개 페이지에서 확인한 소수의 거래 사실을 출처와 함께 제공하는 조사판입니다. 실시간 매물 데이터나 서울·경기 전수 통계가 아닙니다.</p><h3>대략적인 가격은 어떻게 표시하나요?</h3><p>확인한 개별 실거래 또는 공개 집계값을 카드에서는 0.1억원 단위로 반올림합니다. 상세에서는 원래 금액·거래일·층·면적과 출처를 보여줍니다. 직거래만 확인되거나 면적을 연결할 근거가 부족하면 가격을 비워 둡니다.</p><h3>네이버 연결</h3><p>단지 식별자가 확인된 곳은 직접 연결합니다. 나머지는 단지명과 주소를 포함한 네이버 검색으로 연결하므로 검색 결과에서 네이버 부동산을 선택해주세요. 로그인이나 서비스 상태에 따라 외부 화면은 달라질 수 있습니다.</p><h3>정식 데이터 연동</h3><p>국토부 실거래가 API 수집기와 CSV 가져오기를 준비했습니다. API 이용 승인과 단지 마스터가 확보되면 400세대 필터, 면적 분류, 해제 거래 제외 및 기간별 대표가격으로 확장할 수 있습니다.</p>${link('https://www.data.go.kr/data/15126468/openapi.do','국토부 아파트 실거래가 API')}${link('https://www.data.go.kr/data/15106861/fileData.do','한국부동산원 단지 식별정보')}<h3>자료별 링크</h3>${state.data.apartments.map(a=>`<p>${link(a.source,a.name+' 단지 정보')}</p>`).join('')}<p>데이터 조사일: ${escape(state.data.updatedAt)}. 취소·정정과 신고 지연에 따라 값이 바뀔 수 있습니다.</p>`,'DATA & SOURCES');}
function privacy(){openModal('금융정보는 내 브라우저 안에',`<p>연봉·자산·부채 입력은 현재 브라우저 메모리에서만 계산하고 서버로 전송하거나 URL에 포함하지 않습니다. 새로고침하면 입력값은 초기화됩니다.</p><p>관심 아파트의 단지 식별자만 이 브라우저에 저장합니다. 외부 링크를 열면 해당 서비스의 정책이 적용됩니다. 화면 글꼴은 Google Fonts에서 불러오며 금융정보를 보내지 않습니다.</p><button class="outline-button" style="margin-top:20px" data-action="clear-saved">저장한 관심 단지 삭제</button>`,'PRIVACY');}
function setPressed(attr,value){document.querySelectorAll(`[${attr}]`).forEach(b=>{const selected=b.getAttribute(attr)===value;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected));});}
function clearFilters(){state.region='all';state.search='';state.affordable=false;state.favoritesOnly=false;$('#search').value='';$('#affordable').checked=false;$('#favorites-only').checked=false;setPressed('data-region','all');renderList();}
function saveFavorites(){try{localStorage.setItem('jip-favorites',JSON.stringify([...state.favorites]));}catch{toast('이 브라우저에서는 관심 단지를 저장할 수 없어요.');}}
document.addEventListener('click',event=>{
  const b=event.target.closest('button');if(!b)return;
  if(b.dataset.region){state.region=b.dataset.region;setPressed('data-region',state.region);renderList();}
  if(b.dataset.area){state.area=b.dataset.area;setPressed('data-area',state.area);renderList();}
  if(b.dataset.detail)detail(b.dataset.detail);
  if(b.dataset.favorite){const id=b.dataset.favorite;state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);saveFavorites();renderList();}
  if(b.dataset.compare){const id=b.dataset.compare;if(state.compared.includes(id)){state.compared=state.compared.filter(x=>x!==id);toast('비교함에서 제외했어요.');}else if(state.compared.length>=3){toast('최대 3개 단지를 비교할 수 있어요.');}else{state.compared.push(id);toast('비교함에 담았어요. 상단 비교함에서 확인하세요.');}renderList();}
  if(b.dataset.removeCompare){state.compared=state.compared.filter(x=>x!==b.dataset.removeCompare);renderList();comparison();}
  const actions={method,policy,sources,comparison,privacy,'clear-filters':clearFilters,'clear-saved':()=>{state.favorites.clear();saveFavorites();renderList();toast('관심 단지를 삭제했어요.');}};
  if(b.dataset.action&&actions[b.dataset.action]){if(!state.data||!state.policy){toast('자료를 불러온 후 다시 시도해주세요.');return;}actions[b.dataset.action]();}
});
$('#search').addEventListener('input',e=>{state.search=e.target.value;renderList();});
$('#sort').addEventListener('change',e=>{state.sort=e.target.value;renderList();});
$('#affordable').addEventListener('change',e=>{state.affordable=e.target.checked;renderList();});
$('#favorites-only').addEventListener('change',e=>{state.favoritesOnly=e.target.checked;renderList();});
form.addEventListener('submit',e=>{e.preventDefault();const p=readProfile(),errors=validateProfile(p);$('#form-error').textContent=errors.join(' ');if(errors.length)return;state.profile=p;renderBudget();renderList();toast('입력한 조건으로 다시 계산했어요.');});
form.addEventListener('reset',()=>{setTimeout(()=>{state.profile=readProfile();$('#form-error').textContent='';renderBudget();renderList();},0);});
$('#close-modal').addEventListener('click',()=>$('#modal').close());
$('#modal').addEventListener('click',e=>{if(e.target!==$('#modal'))return;const r=$('#modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('#modal').close();});
try{
  const [data,policyData]=await Promise.all(['./data/apartments.json','./data/policy.json'].map(async url=>{const r=await fetch(url);if(!r.ok)throw Error('HTTP '+r.status);return r.json();}));
  state.data=data;state.policy=policyData;renderBudget();renderList();
}catch(error){$('#apartments').innerHTML='<div class="empty-state">자료를 불러오지 못했어요.<br>인터넷 연결을 확인하고 새로고침해주세요.</div>';$('#result-count').textContent='데이터 로드 실패';console.error('Dataset load failed:',error.message);}
